# Generated by Django 3.2.11 on 2022-02-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('', 'Category'), ('Cartoon', 'Cartoon'), ('Documentary', 'Documentary'), ('Action', 'Action')], max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
